### ISSUE TITLE
Support `application/jwk-set+json` content type when processing responses from JWKS Endpoint

### ISSUE THREAD

**Issue by saskenuba** [ramosbugs/openidconnect-rs#11]
`openidconnect-rs` is not considering the `application/jwk-set+json` content type when processing responses from the JWKS endpoint.

Accordingly, with the [specs](https://tools.ietf.org/html/rfc7517) the application/jwk-set+json can be used to indicate that the content is a JWKS.

To reproduce, just set the issuer url to an endpoint which has JWKS that responds with the header `application/jwk-set+json; charset=UTF-8`. Can we make this available as valid content-type?

I found this issue when integrating with Identity Server 4.

Thanks!

**Comment by saskenuba** [comment]
I have the following stack trace:
```
thread 'openid::tests::testinho' panicked at 'called `Result::unwrap()` on an `Err` value: Response(200, [123, 34, 107, 101, 121, 115, 34, 58, 91, 123, 34, 107, 116, 121, 34, 58, 34, 82, 83, 65, 34, 44, 34, 117, 115, 101, 34, 58, 34, 115, 105, 103, 34, 44, 34, 107, 105, 100, 34, 58, 34, 52, 73, 102, 109, 117, 66, 107, 83, 99, 82, 95, 71, 110, 75, 74, 118, 119, 57, 68, 72, 54, 65, 34, 44, 34, 101, 34, 58, 34, 65, 81, 65, 66, 34, 44, 34, 110, 34, 58, 34, 117, 120, 50, 120, 71, 107, 107, 113, 106, 75, 82, 98, 115, 49, 87, 48, 121, 89, 71, 100, 53, 84, 48, 102, 45, 99, 48, 75, 56, 81, 72, 54, 68, 101, 78, 101, 110, 53, 108, 67, 81, 87, 69, 101, 77, 79, 85, 89, 107, 82, 70, 51, 71, 45, 95, 118, 55, 98, 120, 99, 86, 98, 84, 104, 69, 115, 115, 54, 65, 87, 109, 119, 79, 116, 109, 88, 103, 74, 97, 101, 80, 66, 85, 90, 90, 87, 49, 102, 67, 105, 120, 80, 88, 101, 84, 79, 111, 85, 82, 115, 52, 66, 52, 122, 84, 78, 55, 95, 66, 90, 45, 116, 90, 122, 74, 85, 87, 86, 49, 76, 108, 57, 53, 69, 77, 50, 74, 110, 119, 53, 73, 51, 73, 105, 80, 49, 113, 51, 71, 109, 104, 55, 82, 54, 98, 115, 121, 83, 111, 71, 103, 109, 103, 50, 74, 108, 48, 118, 100, 79, 54, 75, 81, 85, 108, 89, 51, 75, 113, 90, 90, 112, 99, 110, 111, 57, 111, 113, 84, 54, 86, 98, 49, 108, 51, 72, 109, 45, 122, 86, 117, 103, 55, 52, 45, 56, 102, 111, 73, 112, 53, 79, 104, 117, 72, 79, 97, 90, 114, 73, 117, 67, 99, 56, 107, 65, 101, 55, 98, 84, 99, 108, 115, 70, 120, 72, 115, 122, 45, 69, 79, 68, 52, 73, 55, 68, 82, 80, 75, 115, 69, 82, 113, 56, 109, 78, 88, 113, 99, 122, 98, 66, 85, 106, 75, 111, 54, 122, 48, 82, 107, 97, 122, 49, 117, 53, 77, 115, 57, 87, 111, 87, 81, 80, 82, 120, 55, 48, 49, 70, 65, 89, 87, 71, 122, 88, 95, 75, 80, 104, 114, 49, 111, 84, 119, 80, 118, 55, 98, 53, 74, 119, 117, 115, 48, 69, 114, 118, 95, 45, 81, 108, 75, 72, 89, 100, 116, 100, 109, 73, 84, 97, 116, 68, 68, 95, 111, 76, 56, 89, 104, 98, 121, 79, 112, 120, 50, 69, 106, 95, 65, 119, 34, 44, 34, 97, 108, 103, 34, 58, 34, 82, 83, 50, 53, 54, 34, 125, 93, 125], "Unexpected response Content-Type: \"application/jwk-set+json; charset=UTF-8\", should be `application/json`")', src/openid.rs:20:29
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1427
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: core::result::Result<T,E>::unwrap
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/result.rs:1003
  15: store_skins::openid::prepare_link
             at src/openid.rs:20
  16: store_skins::openid::tests::testinho
             at src/openid.rs:52
  17: store_skins::openid::tests::testinho::{{closure}}
             at src/openid.rs:51
  18: core::ops::function::FnOnce::call_once
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/ops/function.rs:232
  19: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/liballoc/boxed.rs:1017
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/panic.rs:318
  21: std::panicking::try::do_call
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/panicking.rs:331
  22: std::panicking::try
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/panicking.rs:274
  23: std::panic::catch_unwind
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/panic.rs:394
  24: test::run_test_in_process
             at src/libtest/lib.rs:542
  25: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:451
```

**Comment by ramosbugs** [comment]
Thanks for filing this issue! 42b4ae84aeec74afbe0af76b3d55671e1b4028c5 should fix it. Please re-open if it doesn't.
